<?php

namespace SunKe\TestBundle\Repository;

/**
 * table_blogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class table_blogRepository extends \Doctrine\ORM\EntityRepository
{
}
