<?php

namespace SunKe\TestBundle\Repository;

/**
 * table_blog_newsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class table_blog_newsRepository extends \Doctrine\ORM\EntityRepository
{
}
