sk_test:
    resource: "@SkTestBundle/Controller/"
    type:     annotation

news:
    resource: "@NewsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
