<?php

namespace SunKe\TestBundle\Repository\Demo;

/**
 * Table_blog_msgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Table_blog_msgRepository extends \Doctrine\ORM\EntityRepository
{
}
